print("THIS PROGRAM IS DESIGNED TO FIND THE AVERAGE SCORE OF FIVE STUDENTS IN AN EXAMINATION")
print("Please enter the score of the student then press enter key")
a=int(input("First Student="))
b=int(input("Second Student="))
c=int(input("Third Student="))
d=int(input("Fourth Student="))
e=int(input("Fiveth Student="))
sum=(a+b+c+d+e)
average=(sum/5)
input(print("The average score of the students is",average))
input(print("Thank you for using this program"))
input(print("Hello World!","Hello World!!","Hello World!!!"))
input(print("Designed by Yusuf Aliyu, Reg No. 1610308027"))
input("\n\nPress the enter key to exit")

