print("PROGRAM FOR FINDING THE ROOTS OF A QUADRATIC EQUATION")
print("ax^2 + bx + c = 0")
a=int(input("a="))
b=int(input("b="))
c=int(input("c="))
d=(b**2-4*a*c)
input(print("The discriminant value is:",d))
if d>=0:
    x1=(((-b)+(d**(1/2)))/(2*a))
    x2=(((-b)-(d**(1/2)))/(2*a))
    print("The roots of the equation are real, hence")
    input(print("The roots of the equation are",x1,"and",x2))
    input("\n\nPress enter key to exit.\n")
else:
    rp=(b/2*a)
    ip=((d/2*a)**(1/2))
    z1=(rp+ip)
    z2=(rp-ip)
    print("The roots of the equation are imaginary, hence")
    input(print("The roots are",z1,"and",z2))
    input("\n\nPress enter key to exit\n.")
